# Generated by Django 6.0.5 on 2026-05-29 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='seller',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller')], default='seller', max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='seller_set', related_query_name='seller', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='seller_set', related_query_name='seller', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='SellerCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('overdue', 'Overdue'), ('paid', 'Paid'), ('settled', 'Settled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='sellerapp.seller')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('seller', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('credit_added', 'Credit Added'), ('payment_received', 'Payment Received')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sellerapp.seller')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sellerapp.sellercustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channels', models.JSONField(default=list)),
                ('message', models.TextField(blank=True)),
                ('is_sent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders_sent', to='sellerapp.seller')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='sellerapp.sellercustomer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='sellerapp.seller')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sellerapp.sellercustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='seller/customer_files/')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_files', to='sellerapp.seller')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sellerapp.sellercustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='sellerapp.seller')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='sellerapp.sellercustomer')),
            ],
        ),
        migrations.CreateModel(
            name='SellerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('reminder_channels', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sellerapp.seller')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(default='staff', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='sellerapp.seller')),
            ],
        ),
    ]
