# Generated by Django 6.0.5 on 2026-05-30 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_sellercustomer_linked_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('message', 'Message'), ('payment', 'Payment'), ('general', 'General'), ('reminder', 'Reminder')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sellerapp.seller')),
                ('seller_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='sellerapp.sellercustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
