# Generated by Django 6.0.5 on 2026-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_sellerdevicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellercustomer',
            name='advance_deposited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellercustomer',
            name='advance_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('credit_added', 'Credit Added'), ('payment_received', 'Payment Received'), ('advance_deposit', 'Advance Deposit'), ('advance_use', 'Advance Use')], max_length=30),
        ),
    ]
