# Generated by Django 6.0.5 on 2026-06-08 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_sellercustomer_advance_deposited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDayDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('activity_date', models.DateField()),
                ('credit_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_digests', to='sellerapp.sellercustomer')),
            ],
            options={
                'ordering': ['-activity_date'],
                'unique_together': {('seller_customer', 'activity_date')},
            },
        ),
    ]
