# Generated by Django 6.0.5 on 2026-06-08 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0007_customerdaydigest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertransaction',
            name='client_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='device_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sellercustomer',
            name='client_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sellercustomer',
            name='device_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['seller', 'updated_at'], name='ledger_seller_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('seller', 'client_id'), name='unique_seller_ledger_client_id'),
        ),
        migrations.AddConstraint(
            model_name='sellercustomer',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('seller', 'client_id'), name='unique_seller_customer_client_id'),
        ),
    ]
