# Generated by Django 6.0.5 on 2026-06-09 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0008_ledgertransaction_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettings',
            name='auto_remind_days_before',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='auto_remind_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='auto_remind_time',
            field=models.CharField(default='09:00', max_length=5),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='daily_summary_channels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='daily_summary_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='daily_summary_time',
            field=models.CharField(default='21:00', max_length=5),
        ),
        migrations.AddField(
            model_name='sellersettings',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sellernotification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('payment', 'Payment'), ('credit', 'Credit'), ('general', 'General'), ('reminder', 'Reminder'), ('overdue', 'Overdue'), ('daily_summary', 'Daily summary')], default='general', max_length=30),
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('reminder_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='sellerapp.sellercustomer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='sellerapp.seller')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['seller', 'customer', 'channel', 'sent_at'], name='reminder_log_dedupe_idx')],
            },
        ),
    ]
