# Generated by Django 6.0.5 on 2026-06-13 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0009_sellersettings_auto_remind_days_before_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNightlyDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=10)),
                ('activity_date', models.DateField()),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-activity_date'],
                'unique_together': {('phone', 'activity_date')},
            },
        ),
    ]
