# Generated by Django 6.0.5 on 2026-08-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0020_teammember_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettings',
            name='eod_excel_backup_enabled',
            field=models.BooleanField(default=True, help_text='Email an end-of-day Excel backup of all ledger transactions to the seller.'),
        ),
    ]
