# Generated by Django 6.0.5 on 2026-08-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0021_sellersettings_eod_excel_backup_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersettings',
            name='eod_excel_backup_time',
            field=models.CharField(default='22:00', max_length=5),
        ),
    ]
