# Generated by Django 6.0.5 on 2026-08-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0024_merge_address_parts_and_excel_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='signup_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='signup_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='signup_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='signup_located_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='signup_region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='signup_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
