# Generated by Django 6.0.5 on 2026-05-30 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_otprecord_customer_role_alter_customer_groups_and_more'),
        ('sellerapp', '0003_sellercustomer_linked_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_accounts', to='sellerapp.seller'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='seller_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_accounts', to='sellerapp.sellercustomer'),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='shop_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='customerapp.customeraccount'),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('payment', 'Payment'), ('general', 'General'), ('message', 'Message'), ('credit', 'Credit')], default='general', max_length=30),
        ),
        migrations.CreateModel(
            name='ShopMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, upload_to='chat/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_messages', to='customerapp.customeraccount')),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_messages', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_messages', to='sellerapp.seller')),
                ('seller_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_messages', to='sellerapp.sellercustomer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
