# Generated by Django 6.0.5 on 2026-06-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_customerdevicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='advance_deposited',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='advance_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('payment', 'Payment'), ('general', 'General'), ('message', 'Message'), ('credit', 'Credit'), ('advance', 'Advance')], default='general', max_length=30),
        ),
    ]
