# Generated by Django 6.0.5 on 2026-06-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0006_customeraccount_advance_deposited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('seller_login', 'Seller login'), ('reset_password', 'Reset password')], max_length=30),
        ),
    ]
