# Generated by Django 6.0.5 on 2026-06-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_alter_otprecord_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersettings',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('payment', 'Payment'), ('general', 'General'), ('message', 'Message'), ('credit', 'Credit'), ('advance', 'Advance'), ('overdue', 'Overdue')], default='general', max_length=30),
        ),
    ]
