# Generated by Django 6.0.5 on 2026-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_customersettings_push_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
