# Generated by Django 6.0.5 on 2026-06-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0009_customer_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmessage',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
