# Generated by Django 6.0.6 on 2026-06-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0011_razorpay_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_ref',
            field=models.CharField(blank=True, help_text='Bank A/C, card last4, cheque no.', max_length=100),
        ),
        migrations.AddField(
            model_name='razorpaypaymentorder',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque'), ('wallet', 'Wallet')], default='upi', max_length=20),
        ),
    ]
