# Generated by Django 6.0.5 on 2026-07-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_legaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='offline_reference',
            field=models.CharField(blank=True, help_text='UPI/bank ref for offline payments', max_length=120),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('offline', 'Offline')], default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Admin who manually recorded this invoice (offline payments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_invoices', to='adminapp.adminuser'),
        ),
    ]
