# Generated by Django 6.0.5 on 2026-07-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_customerbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='tax_type',
            field=models.CharField(choices=[('cgst_sgst', 'CGST + SGST (intra-state)'), ('igst', 'IGST (inter-state)')], default='cgst_sgst', help_text='Decided at invoice creation from the seller GSTIN state code vs supplier state; frozen thereafter', max_length=20),
        ),
    ]
