# Generated by Django 6.0.5 on 2026-08-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_telegrammessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminalert',
            name='type',
            field=models.CharField(choices=[('sms_failed', 'SMS Failed'), ('trial_expiring', 'Trial Expiring'), ('suspension', 'Suspension'), ('sync_error', 'Sync Error'), ('telegram_message', 'Telegram Message')], max_length=30),
        ),
    ]
