# Generated by Django 6.0.5 on 2026-08-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_alter_adminalert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='direction',
            field=models.CharField(choices=[('in', 'Incoming'), ('out', 'Outgoing')], default='in', max_length=3),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_replies_sent', to='adminapp.adminuser'),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='raw_update',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
