# Generated by Django 6.0.5 on 2026-08-07 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_telegrammessage_direction_telegrammessage_sent_by_and_more'),
        ('sellerapp', '0022_sellersettings_eod_excel_backup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_chat_links', to='sellerapp.seller')),
            ],
        ),
    ]
