# Generated by Django 6.0.5 on 2026-08-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_telegramchatlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='message_thread_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
