# Generated by Django 6.0.5 on 2026-08-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_telegrammessage_message_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
