# Generated by Django 6.0.5 on 2026-08-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_telegrammessage_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='crm_invoice_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='crm_invoice_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='crm_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='crm_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
