# Generated by Django 6.0.5 on 2026-08-11 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_subscriptioninvoice_crm_invoice_id_and_more'),
        ('sellerapp', '0024_merge_address_parts_and_excel_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelReportAddonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('duration_days', models.PositiveIntegerField(help_text='Access granted per purchase')),
                ('price_inr', models.DecimalField(decimal_places=2, help_text='Exclusive of GST', max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'duration_days'],
            },
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='addon_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sellerapp.sellerexcelreportorder'),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='kind',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('addon_excel', 'Excel report add-on'), ('addon_sms', 'SMS pack')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='plan_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='sms_pack_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sellerapp.sellersmspackorder'),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='adminapp.sellersubscription'),
        ),
    ]
