# Generated by Django 6.0.5 on 2026-08-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_adminalert_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='crm_receipt_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='crm_receipt_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='crm_receipt_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='crm_receipt_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
