"""
Django settings for easyudhar project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n7oo(s5n6kh_w^7k9-^vda(yt^3=02w9dip0+u2)_9n)@yy*k@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'customerapp',
    'sellerapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'easyudhar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'easyudhar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'customerapp.Customer'

AUTHENTICATION_BACKENDS = [
    'sellerapp.authentication.SellerBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# Firebase Cloud Messaging — see easyudhar/firebase/
# Copy google-services.json here (optional; project_id can also be set via env).
# Download service-account.json from Firebase Console → Project settings → Service accounts.
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', '').strip()
FIREBASE_CREDENTIALS_PATH = os.environ.get('FIREBASE_CREDENTIALS_PATH', '').strip()
_default_firebase_creds = BASE_DIR / 'firebase' / 'service-account.json'
if not FIREBASE_CREDENTIALS_PATH and _default_firebase_creds.exists():
    FIREBASE_CREDENTIALS_PATH = str(_default_firebase_creds)
if not FIREBASE_PROJECT_ID:
    _google_services = BASE_DIR / 'firebase' / 'google-services.json'
    if _google_services.exists():
        import json as _json

        try:
            with open(_google_services, encoding='utf-8') as _f:
                FIREBASE_PROJECT_ID = _json.load(_f).get('project_id', '').strip()
        except (OSError, _json.JSONDecodeError):
            pass
# When org policy blocks service-account key download, use:
#   FIREBASE_USE_ADC=true  +  gcloud auth application-default login
FIREBASE_USE_ADC = os.environ.get('FIREBASE_USE_ADC', '').strip()

# Nimbus SMS — credit given & payment received (DLT: Service / Sub-category Implicit)
# API: GET http://nimbusit.net/api/pushsms?user=&authkey=&sender=&mobile=&text=&entityid=&templateid=&rpt=1
# Env vars override defaults below when set.
NIMBUS_SMS_ENABLED = os.environ.get('NIMBUS_SMS_ENABLED', 'true').strip().lower() in (
    '1',
    'true',
    'yes',
)
NIMBUS_USER_ID = os.environ.get('NIMBUS_USER_ID', 'EAZYUDHAR').strip()
NIMBUS_PASSWORD = os.environ.get('NIMBUS_PASSWORD', 'EAZYUDHAR').strip()
NIMBUS_AUTH_KEY = os.environ.get('NIMBUS_AUTH_KEY', '92ppqbuusFs').strip()
NIMBUS_DLT_ENTITY_ID = os.environ.get('NIMBUS_DLT_ENTITY_ID', '1201177925490858797').strip()
# API sender header (6 chars) — must match Nimbus portal "Select Sender" (EAZYUD).
# "INWIZY" at end of template text is message body only, not this sender field.
NIMBUS_SENDER_ID = os.environ.get('NIMBUS_SENDER_ID', 'EAZYUD').strip()
NIMBUS_API_URL = os.environ.get(
    'NIMBUS_API_URL',
    'http://nimbusit.net/api/pushsms',
).strip()
NIMBUS_CREDIT_TEMPLATE_ID = os.environ.get(
    'NIMBUS_CREDIT_TEMPLATE_ID',
    '1207178013086303958',
).strip()
NIMBUS_PAYMENT_TEMPLATE_ID = os.environ.get(
    'NIMBUS_PAYMENT_TEMPLATE_ID',
    '1207178013900576203',
).strip()
# DLT-approved templates (CREDIT3 / PAYMENT3) — wording must not change.
NIMBUS_CREDIT_SMS_TEXT = os.environ.get(
    'NIMBUS_CREDIT_SMS_TEXT',
    'Credit of Rs. {#var#} added to your account by {#var#} Check Balance and Details on {#var#} - EAZYUDHAR by INWIZY',
).strip()
NIMBUS_PAYMENT_SMS_TEXT = os.environ.get(
    'NIMBUS_PAYMENT_SMS_TEXT',
    'Payment of Rs. {#var#} credited to your account by {#var#} Check Balance and Details on {#var#} - EAZYUDHAR by INWIZY',
).strip()
# Third {#var#} in both templates — platform name shown after "Check Balance and Details on"
NIMBUS_SMS_PLATFORM_NAME = os.environ.get('NIMBUS_SMS_PLATFORM_NAME', 'EAZYUDHAR').strip()
# DLT: each {#var#} value is often max 30 chars — we truncate in code if longer.
NIMBUS_SMS_VAR_MAX_LENGTH = int(os.environ.get('NIMBUS_SMS_VAR_MAX_LENGTH', '30'))
# Mobile: 10-digit local, or set prefix e.g. 91 -> sends 917579320174 (try if all msgs fail delivery).
NIMBUS_MOBILE_PREFIX = os.environ.get('NIMBUS_MOBILE_PREFIX', '').strip()
# DLT route — match Nimbus portal: Category = Service, Sub Category = Implicit
NIMBUS_SMS_CATEGORY = os.environ.get('NIMBUS_SMS_CATEGORY', 'service').strip()
NIMBUS_SMS_SUB_CATEGORY = os.environ.get('NIMBUS_SMS_SUB_CATEGORY', 'implicit').strip()
# Optional extra API keys if Nimbus support asks for different names (e.g. smstype=SI)
NIMBUS_SMS_EXTRA_PARAMS = os.environ.get('NIMBUS_SMS_EXTRA_PARAMS', '').strip()
NIMBUS_REQUEST_TIMEOUT = int(os.environ.get('NIMBUS_REQUEST_TIMEOUT', '30'))