"""
Django settings for easyudhar project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n7oo(s5n6kh_w^7k9-^vda(yt^3=02w9dip0+u2)_9n)@yy*k@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'customerapp',
    'sellerapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'easyudhar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'easyudhar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Local dev: run first (keep window open):
#   ssh -L 3307:127.0.0.1:3306 root@server.inwizy.com
# On VPS (app + DB same server): DB_HOST=127.0.0.1 DB_PORT=3306
# Direct remote (if firewall allows 3306): DB_HOST=server.inwizy.com DB_PORT=3306
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': os.environ.get('DB_NAME', 'eazyudhar'),
#         'USER': os.environ.get('DB_USER', 'eazyudhar'),
#         'PASSWORD': os.environ.get('DB_PASSWORD', 'Eazy@2026#'),
#         'HOST': os.environ.get('DB_HOST', '193.180.212.163'),
#         'PORT': os.environ.get('DB_PORT', '3306'),
#         'OPTIONS': {
#             'charset': 'utf8mb4',
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     },
# }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'customerapp.Customer'

AUTHENTICATION_BACKENDS = [
    'sellerapp.authentication.SellerBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.environ.get('JWT_ACCESS_TOKEN_MINUTES', '60'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.environ.get('JWT_REFRESH_TOKEN_DAYS', '30'))
    ),
    'ROTATE_REFRESH_TOKENS': True,
}

# Firebase Cloud Messaging — see easyudhar/firebase/
# Copy google-services.json here (optional; project_id can also be set via env).
# Download service-account.json from Firebase Console → Project settings → Service accounts.
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', '').strip()
FIREBASE_CREDENTIALS_PATH = os.environ.get('FIREBASE_CREDENTIALS_PATH', '').strip()
_default_firebase_creds = BASE_DIR / 'firebase' / 'service-account.json'
if not FIREBASE_CREDENTIALS_PATH and _default_firebase_creds.exists():
    FIREBASE_CREDENTIALS_PATH = str(_default_firebase_creds)
if not FIREBASE_PROJECT_ID:
    _google_services = BASE_DIR / 'firebase' / 'google-services.json'
    if _google_services.exists():
        import json as _json

        try:
            with open(_google_services, encoding='utf-8') as _f:
                FIREBASE_PROJECT_ID = _json.load(_f).get('project_id', '').strip()
        except (OSError, _json.JSONDecodeError):
            pass
# When org policy blocks service-account key download, use:
#   FIREBASE_USE_ADC=true  +  gcloud auth application-default login
FIREBASE_USE_ADC = os.environ.get('FIREBASE_USE_ADC', '').strip()

# Nimbus SMS — credit given & payment received (DLT: Service / Sub-category Implicit)
# API: GET http://nimbusit.net/api/pushsms?user=&authkey=&sender=&mobile=&text=&entityid=&templateid=&rpt=1
# Env vars override defaults below when set.
NIMBUS_SMS_ENABLED = os.environ.get('NIMBUS_SMS_ENABLED', 'true').strip().lower() in (
    '1',
    'true',
    'yes',
)
NIMBUS_USER_ID = os.environ.get('NIMBUS_USER_ID', 'EAZYUDHAR').strip()
NIMBUS_PASSWORD = os.environ.get('NIMBUS_PASSWORD', 'EAZYUDHAR').strip()
NIMBUS_AUTH_KEY = os.environ.get('NIMBUS_AUTH_KEY', '92ppqbuusFs').strip()
NIMBUS_DLT_ENTITY_ID = os.environ.get('NIMBUS_DLT_ENTITY_ID', '1201177925490858797').strip()
# API sender header (6 chars) — must match Nimbus portal "Select Sender" (EAZYUD).
# "INWIZY" at end of template text is message body only, not this sender field.
NIMBUS_SENDER_ID = os.environ.get('NIMBUS_SENDER_ID', 'EAZYUD').strip()
NIMBUS_API_URL = os.environ.get(
    'NIMBUS_API_URL',
    'http://nimbusit.net/api/pushsms',
).strip()
NIMBUS_CREDIT_TEMPLATE_ID = os.environ.get(
    'NIMBUS_CREDIT_TEMPLATE_ID',
    '1207178013086303958',
).strip()
NIMBUS_PAYMENT_TEMPLATE_ID = os.environ.get(
    'NIMBUS_PAYMENT_TEMPLATE_ID',
    '1207178013900576203',
).strip()
# Login OTP — register template on Nimbus DLT portal, then set template id here.
NIMBUS_OTP_TEMPLATE_ID = os.environ.get('NIMBUS_OTP_TEMPLATE_ID', '').strip()
NIMBUS_OTP_SMS_TEXT = os.environ.get(
    'NIMBUS_OTP_SMS_TEXT',
    'Your OTP for login to EAZYUDHAR is {#var#}. Valid for 5 minutes. Do not share. - EAZYUDHAR by INWIZY',
).strip()
# DLT-approved templates (CREDIT3 / PAYMENT3) — wording must not change.
NIMBUS_CREDIT_SMS_TEXT = os.environ.get(
    'NIMBUS_CREDIT_SMS_TEXT',
    'Credit of Rs. {#var#} added to your account by {#var#} Check Balance and Details on {#var#} - EAZYUDHAR by INWIZY',
).strip()
NIMBUS_PAYMENT_SMS_TEXT = os.environ.get(
    'NIMBUS_PAYMENT_SMS_TEXT',
    'Payment of Rs. {#var#} credited to your account by {#var#} Check Balance and Details on {#var#} - EAZYUDHAR by INWIZY',
).strip()
# Third {#var#} in nightly digest SMS — customer's day-statement link (not truncated).
PUBLIC_STATEMENT_BASE_URL = os.environ.get(
    'PUBLIC_STATEMENT_BASE_URL',
    'https://eazy-udhar-backend.onrender.com',
).strip().rstrip('/')
# Per-txn SMS replaced by nightly digest; third {#var#} is statement URL on credit/payment templates.
NIMBUS_SMS_PLATFORM_NAME = os.environ.get('NIMBUS_SMS_PLATFORM_NAME', 'EAZYUDHAR').strip()
# DLT: shop name / amount vars are often max 30 chars — we truncate in code if longer.
NIMBUS_SMS_VAR_MAX_LENGTH = int(os.environ.get('NIMBUS_SMS_VAR_MAX_LENGTH', '30'))
# Statement link in SMS: 0 = do not truncate (full URL in third {#var#}).
NIMBUS_SMS_LINK_VAR_MAX_LENGTH = int(os.environ.get('NIMBUS_SMS_LINK_VAR_MAX_LENGTH', '0'))
# Mobile: 10-digit local, or set prefix e.g. 91 -> sends 917579320174 (try if all msgs fail delivery).
NIMBUS_MOBILE_PREFIX = os.environ.get('NIMBUS_MOBILE_PREFIX', '').strip()
# DLT route — match Nimbus portal: Category = Service, Sub Category = Implicit
NIMBUS_SMS_CATEGORY = os.environ.get('NIMBUS_SMS_CATEGORY', 'service').strip()
NIMBUS_SMS_SUB_CATEGORY = os.environ.get('NIMBUS_SMS_SUB_CATEGORY', 'implicit').strip()
# Optional extra API keys if Nimbus support asks for different names (e.g. smstype=SI)
NIMBUS_SMS_EXTRA_PARAMS = os.environ.get('NIMBUS_SMS_EXTRA_PARAMS', '').strip()
NIMBUS_REQUEST_TIMEOUT = int(os.environ.get('NIMBUS_REQUEST_TIMEOUT', '30'))

# --- Production / Render (admin login CSRF, HTTPS behind proxy) ---
_render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
_csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()

csrf_trusted_origins = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://eazy-udhar-backend.onrender.com',
]
if _render_hostname:
    csrf_trusted_origins.append(f'https://{_render_hostname}')
if _csrf_origins_env:
    csrf_trusted_origins.extend(
        origin.strip()
        for origin in _csrf_origins_env.split(',')
        if origin.strip()
    )
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(csrf_trusted_origins))

if os.environ.get('RENDER') or _render_hostname:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    if _render_hostname and _render_hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['*', _render_hostname]

# Postmark SMTP — login OTP (replaces Nimbus SMS OTP)
POSTMARK_SERVER_TOKEN = os.environ.get(
    'POSTMARK_SERVER_TOKEN',
    '560b9e20-b49f-4a1c-9a46-45df5610caf1',
).strip()
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.postmarkapp.com').strip()
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', POSTMARK_SERVER_TOKEN).strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', POSTMARK_SERVER_TOKEN).strip()
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').strip().lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').strip().lower() in ('1', 'true', 'yes')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '30'))
# Must be a verified sender signature in Postmark (inwizy.com domain)
DEFAULT_FROM_EMAIL = os.environ.get('OTP_FROM_EMAIL', 'alerts@inwizy.com').strip()
OTP_EMAIL_SUBJECT = os.environ.get('OTP_EMAIL_SUBJECT', 'Your EAZYUDHAR login code').strip()
OTP_EXPIRY_MINUTES = int(os.environ.get('OTP_EXPIRY_MINUTES', '5'))
OTP_RESEND_COOLDOWN_SECONDS = int(os.environ.get('OTP_RESEND_COOLDOWN_SECONDS', '60'))
OTP_EMAIL_LOGO_URL = os.environ.get(
    'OTP_EMAIL_LOGO_URL',
    'https://res.cloudinary.com/dm2pfuzxn/image/upload/v1780986731/EazyUdhar_logo_jg0ybi.png',
).strip()

# Reminder / daily summary SMS (DLT templates on Nimbus)
NIMBUS_REMINDER_TEMPLATE_ID = os.environ.get('NIMBUS_REMINDER_TEMPLATE_ID', '').strip()
NIMBUS_REMINDER_SMS_TEXT = os.environ.get(
    'NIMBUS_REMINDER_SMS_TEXT',
    'Reminder: Rs. {#var#} outstanding at {#var#}. Dear {#var#}, please pay. - EAZYUDHAR',
).strip()
NIMBUS_SUMMARY_TEMPLATE_ID = os.environ.get('NIMBUS_SUMMARY_TEMPLATE_ID', '').strip()

# WhatsApp Cloud API (optional — manual remind when configured)
WHATSAPP_API_ENABLED = os.environ.get('WHATSAPP_API_ENABLED', 'false').strip().lower() in (
    '1',
    'true',
    'yes',
)
WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN', '').strip()
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '').strip()
WHATSAPP_API_VERSION = os.environ.get('WHATSAPP_API_VERSION', 'v21.0').strip()